version: "3.7"

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "19090:19090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: always
  grafana:
    image: "grafana/grafana-enterprise"
    container_name: grafana
    ports:
      - "13000:13000"
    restart: always
    depends_on:
      - prometheus
    privileged: true
