-- select * from USER_CONSTRAINTS;
--
-- select table_name, column_name, NULLABLE --, CONSTRAINT_TYPE
-- from USER_TAB_COLUMNS
-- where column_name in (select column_name
--                       from (select column_name, count(*) cnt from USER_TAB_COLUMNS group by column_name)
--                       where cnt > 1) order by column_name, NULLABLE;
--
--
--
-- select * from USER_CONSTRAINTS where CONSTRAINT_TYPE = 'R' order by LAST_CHANGE;

ALTER TABLE  TBL_BOARD      ADD CONSTRAINT  FK_TBL_BOARD_BGNO            FOREIGN KEY  (BGNO)       REFERENCES  TBL_BOARDGROUP  (BGNO);
ALTER TABLE  TBL_BOARDREAD  ADD CONSTRAINT  FK_TBL_BOARDREAD_BRDNO       FOREIGN KEY  (BRDNO)      REFERENCES  TBL_BOARD       (BRDNO);
ALTER TABLE  TBL_BOARDREPLY ADD CONSTRAINT  FK_TBL_BOARDREPLY_BRDNO      FOREIGN KEY  (BRDNO)      REFERENCES  TBL_BOARD       (BRDNO);
ALTER TABLE  TBL_BOARDLIKE  ADD CONSTRAINT  FK_TBL_BOARDLIKE_BRDNO       FOREIGN KEY  (BRDNO)      REFERENCES  TBL_BOARD       (BRDNO);
ALTER TABLE  TBL_BOARDFILE  ADD CONSTRAINT  FK_TBL_BOARDFILE_BRDNO       FOREIGN KEY  (BRDNO)      REFERENCES  TBL_BOARD       (BRDNO);
ALTER TABLE  COM_USER       ADD CONSTRAINT  FK_COM_USER_DEPTNO           FOREIGN KEY  (DEPTNO)     REFERENCES  COM_DEPT        (DEPTNO);
ALTER TABLE  SGN_SIGN       ADD CONSTRAINT  FK_SGN_SIGN_DOCNO            FOREIGN KEY  (DOCNO)      REFERENCES  SGN_DOC         (DOCNO);
ALTER TABLE  SGN_DOCFILE    ADD CONSTRAINT  FK_SGN_DOCFILE_DOCNO         FOREIGN KEY  (DOCNO)      REFERENCES  SGN_DOC         (DOCNO);
ALTER TABLE  SGN_DOC        ADD CONSTRAINT  FK_SGN_DOC_DTNO              FOREIGN KEY  (DTNO)       REFERENCES  SGN_DOCTYPE     (DTNO);
ALTER TABLE  EML_MAIL       ADD CONSTRAINT  FK_EML_MAIL_EMINO            FOREIGN KEY  (EMINO)      REFERENCES  EML_MAILINFO    (EMINO);
ALTER TABLE  EML_MAILFILE   ADD CONSTRAINT  FK_EML_MAILFILE_EMNO         FOREIGN KEY  (EMNO)       REFERENCES  EML_MAIL        (EMNO);
ALTER TABLE  EML_ADDRESS    ADD CONSTRAINT  FK_EML_ADDRESS_EMNO          FOREIGN KEY  (EMNO)       REFERENCES  EML_MAIL        (EMNO);
ALTER TABLE  PRJ_TASK       ADD CONSTRAINT  FK_PRJ_TASK_PRNO             FOREIGN KEY  (PRNO)       REFERENCES  PRJ_PROJECT     (PRNO);
ALTER TABLE  SGN_PATHUSER   ADD CONSTRAINT  FK_SGN_PATHUSER_SPNO         FOREIGN KEY  (SPNO)       REFERENCES  SGN_PATH        (SPNO);
ALTER TABLE  SCH_DETAIL     ADD CONSTRAINT  FK_SCH_DETAIL_SSNO           FOREIGN KEY  (SSNO)       REFERENCES  SCH_SCHEDULE    (SSNO);
ALTER TABLE  PRJ_TASKUSER   ADD CONSTRAINT  FK_PRJ_TASKUSER_TSNO         FOREIGN KEY  (TSNO)       REFERENCES  PRJ_TASK        (TSNO);
ALTER TABLE  PRJ_TASKFILE   ADD CONSTRAINT  FK_PRJ_TASKFILE_TSNO         FOREIGN KEY  (TSNO)       REFERENCES  PRJ_TASK        (TSNO);
ALTER TABLE  EML_MAIL       ADD CONSTRAINT  FK_EML_MAIL_USERNO           FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  SCH_SCHEDULE   ADD CONSTRAINT  FK_SCH_SCHEDULE_USERNO       FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  SGN_DOC        ADD CONSTRAINT  FK_SGN_DOC_USERNO            FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  EML_MAILINFO   ADD CONSTRAINT  FK_EML_MAILINFO_USERNO       FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  SGN_PATHUSER   ADD CONSTRAINT  FK_SGN_PATHUSER_USERNO       FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  SGN_SIGN       ADD CONSTRAINT  FK_SGN_SIGN_USERNO           FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  SGN_PATH       ADD CONSTRAINT  FK_SGN_PATH_USERNO           FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  TBL_BOARDREAD  ADD CONSTRAINT  FK_TBL_BOARDREAD_USERNO      FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  PRJ_TASKUSER   ADD CONSTRAINT  FK_PRJ_TASKUSER_USERNO       FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  TBL_CRUD       ADD CONSTRAINT  FK_TBL_CRUD_USERNO           FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  COM_LOGINOUT   ADD CONSTRAINT  FK_COM_LOGINOUT_USERNO       FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  TBL_BOARDLIKE  ADD CONSTRAINT  FK_TBL_BOARDLIKE_USERNO      FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  TBL_BOARD      ADD CONSTRAINT  FK_TBL_BOARD_USERNO          FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  PRJ_PROJECT    ADD CONSTRAINT  FK_PRJ_PROJECT_USERNO        FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  TBL_BOARDREPLY ADD CONSTRAINT  FK_TBL_BOARDREPLY_USERNO     FOREIGN KEY  (USERNO)     REFERENCES  COM_USER        (USERNO);
ALTER TABLE  COM_CODE_V2    ADD CONSTRAINT  FK_COM_CODE_V2_CHGUSERNO     FOREIGN KEY  (CHGUSERNO)  REFERENCES  COM_USER        (USERNO);
ALTER TABLE  TBL_BOARD      ADD CONSTRAINT  FK_TBL_BOARD_CHGUSERNO       FOREIGN KEY  (CHGUSERNO)  REFERENCES  COM_USER        (USERNO);
ALTER TABLE  TBL_BOARDREPLY ADD CONSTRAINT  FK_TBL_BOARDREPLY_CHGUSERNO  FOREIGN KEY  (CHGUSERNO)  REFERENCES  COM_USER        (USERNO);

ALTER TABLE  COM_MENU       ADD CONSTRAINT FK_COM_MENU_REGUSERNO         FOREIGN KEY (REGUSERNO)   REFERENCES  COM_USER         (USERNO);
ALTER TABLE  COM_MENU       ADD CONSTRAINT FK_COM_MENU_CHGUSERNO         FOREIGN KEY (CHGUSERNO)   REFERENCES  COM_USER         (USERNO);
ALTER TABLE  COM_MENU       ADD CONSTRAINT FK_COM_MENU_MNU_PARENT        FOREIGN KEY (MNU_PARENT)  REFERENCES  COM_MENU         (MNU_NO);

ALTER TABLE  COM_CODE_V2    drop CONSTRAINT  FK_COM_CODE_V2_CHGUSERNO;
