-- DROP SEQUENCE PRNO_SEQ;
CREATE SEQUENCE PRNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE TSNO_SEQ;
CREATE SEQUENCE TSNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

CREATE SEQUENCE FILENO_TASK_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE DEPTNO_SEQ;
CREATE SEQUENCE DEPTNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE USERNO_SEQ;
CREATE SEQUENCE USERNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE BRDNO_SEQ;
CREATE SEQUENCE BRDNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE FILENO_SEQ;
CREATE SEQUENCE FILENO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE BLNO_SEQ;
CREATE SEQUENCE BLNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

--미사용 -- DROP SEQUENCE RENO_SEQ;
CREATE SEQUENCE RENO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE BGNO_SEQ;
CREATE SEQUENCE BGNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE CRNO_SEQ;
CREATE SEQUENCE CRNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

--DROP SEQUENCE LNO_SEQ;
CREATE SEQUENCE LNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE CRNO_SEQ;
CREATE SEQUENCE CRNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE EMNO_SEQ;
CREATE SEQUENCE EMNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE FILENO_EML_SEQ;
CREATE SEQUENCE FILENO_EML_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE EMINO_SEQ;
CREATE SEQUENCE EMINO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE SHNO_SEQ;
CREATE SEQUENCE SHNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE SSNO_SEQ;
CREATE SEQUENCE SSNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE DOCNO_SEQ;
CREATE SEQUENCE DOCNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE FILENO_SGN_SEQ;
CREATE SEQUENCE FILENO_SGN_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE DTNO_SEQ;
CREATE SEQUENCE DTNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE SPNO_SEQ;
CREATE SEQUENCE SPNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE SSNO_SIGN_SEQ;
CREATE SEQUENCE SSNO_SIGN_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE CDNO_SEQ;
CREATE SEQUENCE CDNO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

-- DROP SEQUENCE MNU_NO_SEQ;
CREATE SEQUENCE MNU_NO_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10; -- 2023-11-03 kbil
