CREATE TABLE PERSISTENT_LOGINS (
    USERNAME VARCHAR2(64) NOT NULL,
    SERIES VARCHAR2(64) PRIMARY KEY,
    TOKEN VARCHAR2(64) NOT NULL,
    LAST_USED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE PERSISTENT_LOGINS IS 'remember-me 토큰 저장소';

CREATE TABLE PRJ_PROJECT (
    PRNO NUMBER(10),
    PRSTARTDATE VARCHAR2(10),
    PRENDDATE   VARCHAR2(10),
    PRTITLE     VARCHAR2(100),
    REGDATE     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    USERNO      NUMBER(10),
    PRSTATUS    CHAR(1),
    DELETEFLAG  CHAR(1) DEFAULT 'N',
    CONSTRAINT  PK_PRJ_PROJECT PRIMARY KEY (PRNO)
);
COMMENT ON TABLE PRJ_PROJECT IS '프로젝트';
COMMENT ON COLUMN PRJ_PROJECT.PRNO IS '프로젝트 번호';
COMMENT ON COLUMN PRJ_PROJECT.PRSTARTDATE IS '시작일자';
COMMENT ON COLUMN PRJ_PROJECT.PRENDDATE IS '종료일자';
COMMENT ON COLUMN PRJ_PROJECT.PRTITLE IS '프로젝트 제목';
COMMENT ON COLUMN PRJ_PROJECT.REGDATE IS '등록일자';
COMMENT ON COLUMN PRJ_PROJECT.USERNO IS '사용자번호';
COMMENT ON COLUMN PRJ_PROJECT.PRSTATUS IS '상태';
COMMENT ON COLUMN PRJ_PROJECT.DELETEFLAG IS '삭제여부';

CREATE TABLE PRJ_TASK (
    PRNO        NUMBER(10),
    TSNO        NUMBER(19) NOT NULL,
    TSPARENT    NUMBER(19),
    TSSORT      NUMBER(7),
    TSTITLE     VARCHAR2(100),
    TSSTARTDATE VARCHAR2(10),
    TSENDDATE   VARCHAR2(10),
    TSENDREAL   VARCHAR2(10),
    TSRATE      NUMBER(5),
    OLDNO       NUMBER(19),
    DELETEFLAG  CHAR(1) DEFAULT 'N',
    CONSTRAINT  PK_PRJ_TASK PRIMARY KEY (TSNO)
);
COMMENT ON TABLE PRJ_TASK IS '프로젝트 업무';
COMMENT ON COLUMN PRJ_TASK.PRNO IS '프로젝트 번호';
COMMENT ON COLUMN PRJ_TASK.TSNO IS '업무번호';
COMMENT ON COLUMN PRJ_TASK.TSPARENT IS '부모업무번호';
COMMENT ON COLUMN PRJ_TASK.TSSORT IS '정렬';
COMMENT ON COLUMN PRJ_TASK.TSTITLE IS '업무 제목';
COMMENT ON COLUMN PRJ_TASK.TSSTARTDATE IS '시작일자';
COMMENT ON COLUMN PRJ_TASK.TSENDDATE IS '종료일자';
COMMENT ON COLUMN PRJ_TASK.TSENDREAL IS '종료일자(실제)';
COMMENT ON COLUMN PRJ_TASK.TSRATE IS '진행율';
COMMENT ON COLUMN PRJ_TASK.OLDNO IS '이전업무번호';
COMMENT ON COLUMN PRJ_TASK.DELETEFLAG IS '삭제여부';

CREATE TABLE PRJ_TASKUSER (
    TSNO   NUMBER(19) NOT NULL,
    USERNO NUMBER(10) NOT NULL,
    CONSTRAINT PK_PRJ_TASKUSER PRIMARY KEY (TSNO, USERNO)
);
COMMENT ON TABLE PRJ_TASKUSER IS '업무할당';
COMMENT ON COLUMN PRJ_TASKUSER.TSNO IS '업무번호';
COMMENT ON COLUMN PRJ_TASKUSER.USERNO IS '사용자번호';

CREATE TABLE PRJ_TASKFILE (
    TSNO     NUMBER(19),
    FILENO   NUMBER(10) NOT NULL,
    FILENAME VARCHAR2(100),
    REALNAME VARCHAR2(30),
    FILESIZE NUMBER(10),
    DELETEFLAG CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_PRJ_TASKFILE PRIMARY KEY (FILENO)
);
COMMENT ON TABLE PRJ_TASKFILE IS '첨부파일';
COMMENT ON COLUMN PRJ_TASKFILE.TSNO IS '업무번호';
COMMENT ON COLUMN PRJ_TASKFILE.FILENO IS '파일번호';
COMMENT ON COLUMN PRJ_TASKFILE.FILENAME IS '파일명';
COMMENT ON COLUMN PRJ_TASKFILE.REALNAME IS '실제파일명';
COMMENT ON COLUMN PRJ_TASKFILE.FILESIZE IS '파일크기';
COMMENT ON COLUMN PRJ_TASKFILE.DELETEFLAG IS '삭제여부'; -- 2023-11-03

CREATE TABLE COM_CODE
(
    CLASSNO NUMBER(10)   NOT NULL,
    CODECD  VARCHAR2(10) NOT NULL,
    CODENM  VARCHAR2(30),
    CONSTRAINT PK_COM_CODE PRIMARY KEY (CLASSNO, CODECD)
);
COMMENT ON TABLE COM_CODE IS '공통코드';
COMMENT ON COLUMN COM_CODE.CLASSNO IS '그릅코드';
COMMENT ON COLUMN COM_CODE.CODECD IS '코드번호';
COMMENT ON COLUMN COM_CODE.CODENM IS '코드명';

CREATE TABLE COM_CODE_V2
(
    CODECD VARCHAR2(5) NOT NULL constraint COM_CODE_V2_PK primary key,
    PCODECD VARCHAR2(5) constraint COM_CODE_V2_FK references COM_CODE_V2,
    CODENM     VARCHAR2(40),
    CODEDESC   VARCHAR2(100),
    DELETEFLAG CHAR(1)         DEFAULT 'N',
    REGDATE    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    REGUSERNO  NUMBER(10),
    CHGDATE    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CHGUSERNO  NUMBER(10),
    constraint COM_CODE_V2_UK
        unique (CODECD, PCODECD)
);
COMMENT ON TABLE COM_CODE_V2 IS '공통코드';
COMMENT ON COLUMN COM_CODE_V2.CODECD IS '코드';
COMMENT ON COLUMN COM_CODE_V2.PCODECD IS '상위코드';
COMMENT ON COLUMN COM_CODE_V2.CODENM IS '코드명';
COMMENT ON COLUMN COM_CODE_V2.CODEDESC IS '코드설명';
COMMENT ON COLUMN COM_CODE_V2.DELETEFLAG IS '사용여부';
COMMENT ON COLUMN COM_CODE_V2.REGDATE IS '등록일자';
COMMENT ON COLUMN COM_CODE_V2.REGUSERNO IS '등록자';
COMMENT ON COLUMN COM_CODE_V2.CHGDATE IS '수정일자';
COMMENT ON COLUMN COM_CODE_V2.CHGUSERNO IS '수정자';

CREATE TABLE COM_DEPT
(
    DEPTNO     NUMBER(10) NOT NULL,
    DEPTNM     VARCHAR2(20),
    PARENTNO   NUMBER(10) DEFAULT 0,
    DELETEFLAG CHAR(1)       DEFAULT 'N',
    CONSTRAINT PK_COM_DEPT PRIMARY KEY (DEPTNO)
);
COMMENT ON TABLE COM_DEPT IS '그룹 부서';
COMMENT ON COLUMN COM_DEPT.DEPTNO IS '부서 번호';
COMMENT ON COLUMN COM_DEPT.DEPTNM IS '부서명';
COMMENT ON COLUMN COM_DEPT.PARENTNO IS '부모 부서';
COMMENT ON COLUMN COM_DEPT.DELETEFLAG IS '삭제 여부';

CREATE TABLE COM_USER
(
    USERNO NUMBER(10) NOT NULL,
    USERID     VARCHAR2(20),
    USERNM     VARCHAR2(20),
    USERPW     VARCHAR2(100),
    USERROLE   CHAR(1),
    PHOTO      VARCHAR2(50),
    DEPTNO     NUMBER(10),
    DELETEFLAG CHAR(1) DEFAULT 'N',
    USERPOS    VARCHAR2(2),
    CONSTRAINT PK_COM_USER PRIMARY KEY (USERNO)
);
COMMENT ON TABLE COM_USER IS '사용자';
COMMENT ON COLUMN COM_USER.USERNO IS '사용자 번호';
COMMENT ON COLUMN COM_USER.USERID IS 'ID';
COMMENT ON COLUMN COM_USER.USERNM IS '이름';
COMMENT ON COLUMN COM_USER.USERPW IS '비밀번호';
COMMENT ON COLUMN COM_USER.USERROLE IS '권한';
COMMENT ON COLUMN COM_USER.PHOTO IS '사진';
COMMENT ON COLUMN COM_USER.DEPTNO IS '부서번호';
COMMENT ON COLUMN COM_USER.DELETEFLAG IS '삭제 여부';
COMMENT ON COLUMN COM_USER.USERPOS IS '직위';

CREATE TABLE TBL_BOARD
(
    BGNO       NUMBER(10)   DEFAULT 0,
    BRDNO      NUMBER(10) NOT NULL,
    BRDTITLE   VARCHAR2(255),
    USERNO     NUMBER(10),
    BRDMEMO    VARCHAR2(4000),
    REGDATE    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    BRDNOTICE  CHAR(1),
    CHGDATE    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CHGUSERNO  NUMBER(10),
    BRDLIKE    NUMBER(10)   DEFAULT 0,
    DELETEFLAG CHAR(1)         DEFAULT 'N',
    ETC1       VARCHAR2(200),
    ETC2       VARCHAR2(200),
    ETC3       VARCHAR2(200),
    ETC4       VARCHAR2(200),
    ETC5       VARCHAR2(200),
    CONSTRAINT PK_TBL_BOARD PRIMARY KEY (BRDNO),
    CONSTRAINT  FK_TBL_BOARD_USERNO FOREIGN KEY (USERNO) REFERENCES COM_USER(USERNO) /*ON DELETE CASCADE*/
);
COMMENT ON TABLE TBL_BOARD IS '게시판';
COMMENT ON COLUMN TBL_BOARD.BGNO IS '게시판 그룹번호';
COMMENT ON COLUMN TBL_BOARD.BRDNO IS '글 번호';
COMMENT ON COLUMN TBL_BOARD.BRDTITLE IS '글 제목';
COMMENT ON COLUMN TBL_BOARD.USERNO IS '작성자';
COMMENT ON COLUMN TBL_BOARD.BRDMEMO IS '글 내용';
COMMENT ON COLUMN TBL_BOARD.REGDATE IS '등록일자';
COMMENT ON COLUMN TBL_BOARD.BRDNOTICE IS '공지사항여부';
COMMENT ON COLUMN TBL_BOARD.CHGDATE IS '마지막 수정일';
COMMENT ON COLUMN TBL_BOARD.CHGUSERNO IS '마지막 수정자';
COMMENT ON COLUMN TBL_BOARD.BRDLIKE IS '좋아요';
COMMENT ON COLUMN TBL_BOARD.DELETEFLAG IS '삭제 여부';
COMMENT ON COLUMN TBL_BOARD.ETC1 IS '기타1';
COMMENT ON COLUMN TBL_BOARD.ETC2 IS '기타2';
COMMENT ON COLUMN TBL_BOARD.ETC3 IS '기타3';
COMMENT ON COLUMN TBL_BOARD.ETC4 IS '기타4';
COMMENT ON COLUMN TBL_BOARD.ETC5 IS '기타5';

CREATE TABLE TBL_BOARDFILE
(
    FILENO   NUMBER(10) NOT NULL,
    BRDNO    NUMBER(10) DEFAULT 0,
    FILENAME VARCHAR2(100),
    REALNAME VARCHAR2(30),
    FILESIZE NUMBER(10),
    DELETEFLAG CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_TBL_BOARDFILE PRIMARY KEY (FILENO)
);
COMMENT ON TABLE TBL_BOARDFILE IS '게시판 첨부파일';
COMMENT ON COLUMN TBL_BOARDFILE.FILENO IS '파일 번호';
COMMENT ON COLUMN TBL_BOARDFILE.BRDNO IS '글번호';
COMMENT ON COLUMN TBL_BOARDFILE.FILENAME IS '파일명';
COMMENT ON COLUMN TBL_BOARDFILE.REALNAME IS '실제파일명';
COMMENT ON COLUMN TBL_BOARDFILE.FILESIZE IS '파일 크기';
COMMENT ON COLUMN TBL_BOARDFILE.DELETEFLAG IS '삭제 여부';

CREATE TABLE TBL_BOARDLIKE
(
    BLNO    NUMBER(10) NOT NULL,
    BRDNO   NUMBER(10)   DEFAULT 0,
    USERNO  NUMBER(10),
    REGDATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TBL_BOARDLIKE PRIMARY KEY (BLNO)
);
COMMENT ON TABLE TBL_BOARDLIKE IS '게시판 좋아요';
COMMENT ON COLUMN TBL_BOARDLIKE.BLNO IS '번호';
COMMENT ON COLUMN TBL_BOARDLIKE.BRDNO IS '글번호';
COMMENT ON COLUMN TBL_BOARDLIKE.USERNO IS '작성자';
COMMENT ON COLUMN TBL_BOARDLIKE.REGDATE IS '등록일';

DROP TABLE TBL_BOARDREPLY;
CREATE TABLE TBL_BOARDREPLY
(
    BRDNO        NUMBER(10) NOT NULL,
    RENO         NUMBER(10) NOT NULL,
    USERNO       NUMBER(10),
    REMEMO       VARCHAR2(500) DEFAULT NULL,
    REPARENT     NUMBER(10)    DEFAULT 0,
    REDEPTH      NUMBER(10),
    REORDER      NUMBER(10),
    REGDATE      TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
    REDELETEFLAG CHAR(1)          DEFAULT 'N',
    CHGDATE      TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
    CHGUSERNO    NUMBER(10),
    REDELDATE    TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
    DELDATE      TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TBL_BOARDREPLY PRIMARY KEY (RENO),
    CONSTRAINT  FK_TBL_BOARDREPLY_BRDNO FOREIGN KEY (BRDNO) REFERENCES TBL_BOARD(BRDNO) /*ON DELETE CASCADE*/
);
COMMENT ON TABLE TBL_BOARDREPLY IS '게시판 댓글';
COMMENT ON COLUMN TBL_BOARDREPLY.BRDNO IS '게시물 번호';
COMMENT ON COLUMN TBL_BOARDREPLY.RENO IS '댓글 번호';
COMMENT ON COLUMN TBL_BOARDREPLY.USERNO IS '작성자';
COMMENT ON COLUMN TBL_BOARDREPLY.REMEMO IS '댓글내용';
COMMENT ON COLUMN TBL_BOARDREPLY.REPARENT IS '부모 댓글';
COMMENT ON COLUMN TBL_BOARDREPLY.REDEPTH IS '깊이';
COMMENT ON COLUMN TBL_BOARDREPLY.REORDER IS '순서';
COMMENT ON COLUMN TBL_BOARDREPLY.REGDATE IS '등록일자';
COMMENT ON COLUMN TBL_BOARDREPLY.REDELETEFLAG IS '삭제여부';
COMMENT ON COLUMN TBL_BOARDREPLY.CHGDATE IS '마지막 수정일';
COMMENT ON COLUMN TBL_BOARDREPLY.CHGUSERNO IS '미자막 수정자';

CREATE TABLE TBL_BOARDREAD
(
    BRDNO   NUMBER(10) NOT NULL,
    USERNO  NUMBER(10) NOT NULL,
    REGDATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TBL_BOARDREAD PRIMARY KEY (BRDNO, USERNO)
);
COMMENT ON TABLE TBL_BOARDREAD IS '게시판읽기';
COMMENT ON COLUMN TBL_BOARDREAD.BRDNO IS '게시물 번호';
COMMENT ON COLUMN TBL_BOARDREAD.USERNO IS '작성자';
COMMENT ON COLUMN TBL_BOARDREAD.REGDATE IS '등록일자';

CREATE TABLE TBL_BOARDGROUP
(
    BGNO       NUMBER(10) NOT NULL,
    BGNAME     VARCHAR2(50),
    BGPARENT   NUMBER(10)   DEFAULT 0,
    DELETEFLAG CHAR(1)         DEFAULT 'N',
    BGUSED     CHAR(1),
    BGREPLY    CHAR(1),
    BGREADONLY CHAR(1),
    BGNOTICE   CHAR(1),
    REGDATE    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CHGDATE    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TBL_BOARDGROUP PRIMARY KEY (BGNO)
);

COMMENT ON TABLE TBL_BOARDGROUP IS '게시판 그룹';
COMMENT ON COLUMN TBL_BOARDGROUP.BGNO IS '게시판 그룹번호';
COMMENT ON COLUMN TBL_BOARDGROUP.BGNAME IS '게시판 그룹명';
COMMENT ON COLUMN TBL_BOARDGROUP.BGPARENT IS '게시판 그룹 부모';
COMMENT ON COLUMN TBL_BOARDGROUP.DELETEFLAG IS '삭제 여부';
COMMENT ON COLUMN TBL_BOARDGROUP.BGUSED IS '사용 여부';
COMMENT ON COLUMN TBL_BOARDGROUP.BGREPLY IS '댓글 사용여부';
COMMENT ON COLUMN TBL_BOARDGROUP.BGREADONLY IS '글쓰기 가능 여부';
COMMENT ON COLUMN TBL_BOARDGROUP.BGNOTICE IS '공지 쓰기  가능 여부';
COMMENT ON COLUMN TBL_BOARDGROUP.REGDATE IS '등록일자';
COMMENT ON COLUMN TBL_BOARDGROUP.CHGDATE IS '변경일자';

CREATE TABLE COM_LOGINOUT
(
    LNO     NUMBER(10) NOT NULL,
    USERNO  NUMBER(10),
    LTYPE   CHAR(1),
    REGDATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_COM_LOGINOUT PRIMARY KEY (LNO)
);
COMMENT ON TABLE COM_LOGINOUT IS '로그인;로그아웃';
COMMENT ON COLUMN COM_LOGINOUT.LNO IS '순번';
COMMENT ON COLUMN COM_LOGINOUT.USERNO IS '로그인 사용자';
COMMENT ON COLUMN COM_LOGINOUT.LTYPE IS '로그인;로그아웃구분';
COMMENT ON COLUMN COM_LOGINOUT.REGDATE IS '등록일자';

CREATE TABLE TBL_CRUD
(
    CRNO       NUMBER(10) NOT NULL,
    CRTITLE    VARCHAR2(255),
    USERNO     NUMBER(10),
    CRMEMO     VARCHAR2(4000),
    REGDATE    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    DELETEFLAG CHAR(1)         DEFAULT 'N',
    CONSTRAINT PK_TBL_CRUD PRIMARY KEY (CRNO)
);
COMMENT ON TABLE TBL_CRUD IS '테이블 CRUD';
COMMENT ON COLUMN TBL_CRUD.CRNO IS '번호';
COMMENT ON COLUMN TBL_CRUD.CRTITLE IS '제목';
COMMENT ON COLUMN TBL_CRUD.USERNO IS '작성자';
COMMENT ON COLUMN TBL_CRUD.CRMEMO IS '내용';
COMMENT ON COLUMN TBL_CRUD.REGDATE IS '등록일자';
COMMENT ON COLUMN TBL_CRUD.DELETEFLAG IS '삭제 여부';

CREATE TABLE COM_DATE
(
    CDNO          NUMBER(19) NOT NULL,
    CDDATE        VARCHAR2(10),
    CDYEAR        NUMBER(4),
    CDMM          NUMBER(2),
    CDDD          NUMBER(2),
    CDWEEKOFYEAR  NUMBER(5),
    CDWEEKOFMONTH NUMBER(5),
    CDWEEK        NUMBER(5),
    CDDAYOFWEEK   NUMBER(5),
    CDLUNARYEAR   NUMBER(4),
    CDLUNARMONTH     NUMBER(2),
    CDLUNARDAY     NUMBER(2),
    CDLUNARLEAP   CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_COM_DATE PRIMARY KEY (CDNO)
);
COMMENT ON TABLE COM_DATE IS '날짜';
COMMENT ON COLUMN COM_DATE.CDNO IS '번호';
COMMENT ON COLUMN COM_DATE.CDDATE IS '날짜';
COMMENT ON COLUMN COM_DATE.CDYEAR IS '년도';
COMMENT ON COLUMN COM_DATE.CDMM IS '월';
COMMENT ON COLUMN COM_DATE.CDDD IS '일';
COMMENT ON COLUMN COM_DATE.CDWEEKOFYEAR IS '연별주차';
COMMENT ON COLUMN COM_DATE.CDWEEKOFMONTH IS '월별주차';
COMMENT ON COLUMN COM_DATE.CDWEEK IS '주';
COMMENT ON COLUMN COM_DATE.CDDAYOFWEEK IS '주별일자';
COMMENT ON COLUMN COM_DATE.CDLUNARYEAR IS '음력년도';
COMMENT ON COLUMN COM_DATE.CDLUNARMONTH IS '음력월';
COMMENT ON COLUMN COM_DATE.CDLUNARDAY IS '음력일';
COMMENT ON COLUMN COM_DATE.CDLUNARLEAP IS '음력윤달여부';

CREATE TABLE EML_ADDRESS
(
    EMNO      NUMBER(10) NOT NULL,
    EASEQ     NUMBER(10) NOT NULL,
    EATYPE    CHAR(1)       NOT NULL,
    EAADDRESS VARCHAR2(150),
    CONSTRAINT PK_EML_ADDRESS PRIMARY KEY (EMNO, EASEQ, EATYPE)
);
COMMENT ON TABLE EML_ADDRESS IS '메일주소';
COMMENT ON COLUMN EML_ADDRESS.EMNO IS '메일번호';
COMMENT ON COLUMN EML_ADDRESS.EASEQ IS '순번';
COMMENT ON COLUMN EML_ADDRESS.EATYPE IS '주소종류';
COMMENT ON COLUMN EML_ADDRESS.EAADDRESS IS '메일주소';

CREATE TABLE EML_MAIL
(
    EMNO       NUMBER(10) NOT NULL,
    EMTYPE     CHAR(1),
    EMSUBJECT  VARCHAR2(150),
    EMFROM     VARCHAR2(150),
    EMCONTENTS VARCHAR2(4000),
    REGDATE    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    USERNO     NUMBER(10) NOT NULL,
    EMINO      NUMBER(10) NOT NULL,
    DELETEFLAG CHAR(1)         DEFAULT 'N',
    CONSTRAINT PK_EML_MAIL PRIMARY KEY (EMNO)
);
COMMENT ON TABLE EML_MAIL IS '메일주소';
COMMENT ON COLUMN EML_MAIL.EMNO IS '메일번호';
COMMENT ON COLUMN EML_MAIL.EMTYPE IS '메일종류';
COMMENT ON COLUMN EML_MAIL.EMSUBJECT IS '제목';
COMMENT ON COLUMN EML_MAIL.EMFROM IS '보낸사람';
COMMENT ON COLUMN EML_MAIL.EMCONTENTS IS '내용';
COMMENT ON COLUMN EML_MAIL.REGDATE IS '작성일';
COMMENT ON COLUMN EML_MAIL.USERNO IS '사용자번호';
COMMENT ON COLUMN EML_MAIL.EMINO IS '메일정보번호';
COMMENT ON COLUMN EML_MAIL.DELETEFLAG IS '삭제여부';

CREATE INDEX IDX_EML_MAIL_01 ON EML_MAIL (EMTYPE, USERNO, EMINO);

CREATE TABLE EML_MAILFILE
(
    FILENO   NUMBER(10) NOT NULL,
    FILENAME VARCHAR2(100),
    REALNAME VARCHAR2(30),
    FILESIZE NUMBER(10),
    EMNO     NUMBER(10) NOT NULL,
    CONSTRAINT PK_EML_MAILFILE PRIMARY KEY (FILENO)
);
COMMENT ON TABLE EML_MAILFILE IS '첨부파일';
COMMENT ON COLUMN EML_MAILFILE.FILENO IS '파일번호';
COMMENT ON COLUMN EML_MAILFILE.FILENAME IS '파일명';
COMMENT ON COLUMN EML_MAILFILE.REALNAME IS '실제파일명';
COMMENT ON COLUMN EML_MAILFILE.FILESIZE IS '파일크기';
COMMENT ON COLUMN EML_MAILFILE.EMNO IS '메일번호';

CREATE TABLE EML_MAILINFO
(
    EMINO       NUMBER(10) NOT NULL,
    EMIIMAP     VARCHAR2(30),
    EMIIMAPPORT VARCHAR2(5),
    EMISMTP     VARCHAR2(30),
    EMISMTPPORT VARCHAR2(5),
    EMIUSER     VARCHAR2(50),
    EMIPW       VARCHAR2(50),
    USERNO      NUMBER(10) NOT NULL,
    REGDATE     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    DELETEFLAG  CHAR(1)         DEFAULT 'N',
    CONSTRAINT PK_EML_MAILINFO PRIMARY KEY (EMINO)
);
COMMENT ON TABLE EML_MAILINFO IS '메일정보';
COMMENT ON COLUMN EML_MAILINFO.EMINO IS '메일정보번호';
COMMENT ON COLUMN EML_MAILINFO.EMIIMAP IS 'IMAP서버주소';
COMMENT ON COLUMN EML_MAILINFO.EMIIMAPPORT IS 'IMAP서버포트';
COMMENT ON COLUMN EML_MAILINFO.EMISMTP IS 'SMTP 서버주소';
COMMENT ON COLUMN EML_MAILINFO.EMISMTPPORT IS 'SMTP 서버포트';
COMMENT ON COLUMN EML_MAILINFO.EMIUSER IS '계정';
COMMENT ON COLUMN EML_MAILINFO.EMIPW IS '비밀번호';
COMMENT ON COLUMN EML_MAILINFO.USERNO IS '사용자번호';
COMMENT ON COLUMN EML_MAILINFO.REGDATE IS '등록일자';
COMMENT ON COLUMN EML_MAILINFO.DELETEFLAG IS '삭제여부';

CREATE TABLE SCH_DETAIL
(
    SSNO     NUMBER(10) NOT NULL,
    SDSEQ    NUMBER(5)  NOT NULL,
    SDDATE   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    SDHOUR   VARCHAR2(2),
    SDMINUTE VARCHAR2(2),
    CONSTRAINT PK_SCH_DETAIL PRIMARY KEY (SSNO, SDSEQ)
);
COMMENT ON TABLE SCH_DETAIL IS '일정상세';
COMMENT ON COLUMN SCH_DETAIL.SSNO IS '일정번호';
COMMENT ON COLUMN SCH_DETAIL.SDSEQ IS '순번';
COMMENT ON COLUMN SCH_DETAIL.SDDATE IS '날짜';
COMMENT ON COLUMN SCH_DETAIL.SDHOUR IS '시간';
COMMENT ON COLUMN SCH_DETAIL.SDMINUTE IS '분';

drop table SCH_HOLIDAY;
CREATE TABLE SCH_HOLIDAY
(
    SHNO       NUMBER(5) NOT NULL,
    SHTITLE    VARCHAR2(20),
    SHYEAR     NUMBER(5),
    SHMONTH    NUMBER(5),
    SHDAY     NUMBER(5),
    SHLUNAR_YN VARCHAR2(1) default 'N',
    SHALT_YN   VARCHAR2(1) default 'N',
    SHTYPE     VARCHAR2(1),
    SHCOLOR    VARCHAR2(10),
    DELETEFLAG CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_SCH_HOLIDAY PRIMARY KEY (SHNO)
);
COMMENT ON TABLE SCH_HOLIDAY IS '공휴일';
COMMENT ON COLUMN SCH_HOLIDAY.SHNO IS '번호';
COMMENT ON COLUMN SCH_HOLIDAY.SHTITLE IS '공휴일명';
COMMENT ON COLUMN SCH_HOLIDAY.SHYEAR is '년(년도 한정 공휴일/임시공휴일)';
COMMENT ON COLUMN SCH_HOLIDAY.SHMONTH IS '월';
COMMENT ON COLUMN SCH_HOLIDAY.SHDAY IS '일';
COMMENT ON COLUMN SCH_HOLIDAY.SHLUNAR_YN is '음력여부';
COMMENT ON COLUMN SCH_HOLIDAY.SHALT_YN is '대체휴무여부';
COMMENT ON COLUMN SCH_HOLIDAY.SHTYPE is '휴무유형(1-당일휴무,3-당일포함 3일휴무)';
COMMENT ON COLUMN SCH_HOLIDAY.SHCOLOR IS '색상';
COMMENT ON COLUMN SCH_HOLIDAY.DELETEFLAG IS '삭제여부';

CREATE TABLE SCH_SCHEDULE
(
    SSNO           NUMBER(10) NOT NULL,
    SSTITLE        VARCHAR2(50),
    SSTYPE         CHAR(1),
    SSSTARTDATE    CHAR(10),
    SSSTARTHOUR    CHAR(2),
    SSSTARTMINUTE  CHAR(2),
    SSENDDATE      VARCHAR2(10),
    SSENDHOUR      CHAR(2),
    SSENDMINUTE    CHAR(2),
    SSREPEATTYPE   CHAR(1),
    SSREPEATOPTION VARCHAR2(2),
    SSREPEATEND    VARCHAR2(10),
    SSCONTENTS     VARCHAR2(4000),
    SSISOPEN       CHAR(1),
    CHGDATE        TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    REGDATE        TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    USERNO         NUMBER(10) NOT NULL,
    DELETEFLAG     CHAR(1)         DEFAULT 'N',
    CONSTRAINT PK_SCH_SCHEDULE PRIMARY KEY (SSNO)
);
COMMENT ON TABLE SCH_SCHEDULE IS '일정';
COMMENT ON COLUMN SCH_SCHEDULE.SSNO IS '일정번호';
COMMENT ON COLUMN SCH_SCHEDULE.SSTITLE IS '일정명';
COMMENT ON COLUMN SCH_SCHEDULE.SSTYPE IS '구분';
COMMENT ON COLUMN SCH_SCHEDULE.SSSTARTDATE IS '시작일';
COMMENT ON COLUMN SCH_SCHEDULE.SSSTARTHOUR IS '시작일-시간';
COMMENT ON COLUMN SCH_SCHEDULE.SSSTARTMINUTE IS '시작일-분';
COMMENT ON COLUMN SCH_SCHEDULE.SSENDDATE IS '종료일';
COMMENT ON COLUMN SCH_SCHEDULE.SSENDHOUR IS '종료일-시간';
COMMENT ON COLUMN SCH_SCHEDULE.SSENDMINUTE IS '종료일-분';
COMMENT ON COLUMN SCH_SCHEDULE.SSREPEATTYPE IS '반복';
COMMENT ON COLUMN SCH_SCHEDULE.SSREPEATOPTION IS '반복옵션';
COMMENT ON COLUMN SCH_SCHEDULE.SSREPEATEND IS '반복종료';
COMMENT ON COLUMN SCH_SCHEDULE.SSCONTENTS IS '내용';
COMMENT ON COLUMN SCH_SCHEDULE.SSISOPEN IS '공개여부';
COMMENT ON COLUMN SCH_SCHEDULE.CHGDATE IS '수정일자';
COMMENT ON COLUMN SCH_SCHEDULE.REGDATE IS '등록일자';
COMMENT ON COLUMN SCH_SCHEDULE.USERNO IS '사용자번호';
COMMENT ON COLUMN SCH_SCHEDULE.DELETEFLAG IS '삭제여부';

CREATE TABLE SGN_DOC
(
    DOCNO       NUMBER(20) NOT NULL,
    DOCTITLE    VARCHAR2(50),
    DOCCONTENTS VARCHAR2(4000),
    DELETEFLAG  CHAR(1)         DEFAULT 'N',
    DOCSTATUS   CHAR(1),
    DOCSTEP     NUMBER(5),
    DTNO        NUMBER(10) NOT NULL,
    CHGDATE     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    REGDATE     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    USERNO      NUMBER(10) NOT NULL,
    DEPTNM      VARCHAR2(20),
    DOCSIGNPATH VARCHAR2(200),
    CONSTRAINT PK_SGN_DOC PRIMARY KEY (DOCNO)
);
COMMENT ON TABLE SGN_DOC IS '결재문서';
COMMENT ON COLUMN SGN_DOC.DOCNO IS '문서번호';
COMMENT ON COLUMN SGN_DOC.DOCTITLE IS '제목';
COMMENT ON COLUMN SGN_DOC.DOCCONTENTS IS '문서내용';
COMMENT ON COLUMN SGN_DOC.DELETEFLAG IS '삭제여부';
COMMENT ON COLUMN SGN_DOC.DOCSTATUS IS '문서상태';
COMMENT ON COLUMN SGN_DOC.DOCSTEP IS '결재단계';
COMMENT ON COLUMN SGN_DOC.DTNO IS '문서양식번호';
COMMENT ON COLUMN SGN_DOC.CHGDATE IS '수정일자';
COMMENT ON COLUMN SGN_DOC.REGDATE IS '등록일자';
COMMENT ON COLUMN SGN_DOC.USERNO IS '사용자번호';
COMMENT ON COLUMN SGN_DOC.DEPTNM IS '부서명';
COMMENT ON COLUMN SGN_DOC.DOCSIGNPATH IS '결재경로문자열';

CREATE TABLE SGN_DOCFILE
(
    FILENO   NUMBER(10) NOT NULL,
    FILENAME VARCHAR2(100),
    REALNAME VARCHAR2(30),
    FILESIZE NUMBER(10),
    DOCNO    NUMBER(20) NOT NULL,
    CONSTRAINT PK_SGN_DOCFILE PRIMARY KEY (FILENO)
);
COMMENT ON TABLE SGN_DOCFILE IS '첨부파일';
COMMENT ON COLUMN SGN_DOCFILE.FILENO IS '파일번호';
COMMENT ON COLUMN SGN_DOCFILE.FILENAME IS '파일명';
COMMENT ON COLUMN SGN_DOCFILE.REALNAME IS '실제파일명';
COMMENT ON COLUMN SGN_DOCFILE.FILESIZE IS '파일크기';
COMMENT ON COLUMN SGN_DOCFILE.DOCNO IS '문서번호';

CREATE TABLE SGN_DOCTYPE
(
    DTNO       NUMBER(10) NOT NULL,
    DTTITLE    VARCHAR2(30),
    DTCONTENTS VARCHAR2(4000),
    DELETEFLAG CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_SGN_DOCTYPE PRIMARY KEY (DTNO)
);
COMMENT ON TABLE SGN_DOCTYPE IS '문서양식종류';
COMMENT ON COLUMN SGN_DOCTYPE.DTNO IS '문서양식번호';
COMMENT ON COLUMN SGN_DOCTYPE.DTTITLE IS '문서양식명';
COMMENT ON COLUMN SGN_DOCTYPE.DTCONTENTS IS '문서양식내용';
COMMENT ON COLUMN SGN_DOCTYPE.DELETEFLAG IS '삭제여부';

CREATE TABLE SGN_PATH
(
    SPNO       NUMBER(10) NOT NULL,
    SPTITLE    VARCHAR2(30),
    REGDATE    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    USERNO     NUMBER(10) NOT NULL,
    SPSIGNPATH VARCHAR2(200),
    CONSTRAINT  PK_SGN_PATH PRIMARY KEY (SPNO)
);
COMMENT ON TABLE SGN_PATH IS '결재경로';
COMMENT ON COLUMN SGN_PATH.SPNO IS '결재경로번호';
COMMENT ON COLUMN SGN_PATH.SPTITLE IS '경로명';
COMMENT ON COLUMN SGN_PATH.REGDATE IS '등록일자';
COMMENT ON COLUMN SGN_PATH.USERNO IS '사용자번호';
COMMENT ON COLUMN SGN_PATH.SPSIGNPATH IS '결재경로문자열';

CREATE TABLE SGN_PATHUSER
(
    SPNO   NUMBER(10) NOT NULL,
    SPUSEQ NUMBER(10) NOT NULL,
    USERNO NUMBER(10) NOT NULL,
    SSTYPE CHAR(1),
    CONSTRAINT PK_SGN_PATHUSER PRIMARY KEY (SPNO, SPUSEQ)
);
COMMENT ON TABLE SGN_PATHUSER IS '결재경로상세-결재자';
COMMENT ON COLUMN SGN_PATHUSER.SPNO IS '결재경로번호';
COMMENT ON COLUMN SGN_PATHUSER.SPUSEQ IS '경로순번';
COMMENT ON COLUMN SGN_PATHUSER.USERNO IS '사용자번호';
COMMENT ON COLUMN SGN_PATHUSER.SSTYPE IS '결재종류';

CREATE TABLE SGN_SIGN
(
    SSNO        NUMBER(10) NOT NULL,
    DOCNO       NUMBER(20) NOT NULL,
    SSSTEP      NUMBER(5),
    SSTYPE      CHAR(1),
    SSRESULT    CHAR(1),
    SSCOMMENT   VARCHAR2(1000),
    RECEIVEDATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    SIGNDATE    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    USERNO      NUMBER(10) NOT NULL,
    USERPOS     VARCHAR2(10),
    CONSTRAINT PK_SGN_SIGN PRIMARY KEY (SSNO, DOCNO)
);
COMMENT ON TABLE SGN_SIGN IS '결재';
COMMENT ON COLUMN SGN_SIGN.SSNO IS '결재번호';
COMMENT ON COLUMN SGN_SIGN.DOCNO IS '문서번호';
COMMENT ON COLUMN SGN_SIGN.SSSTEP IS '결재단계';
COMMENT ON COLUMN SGN_SIGN.SSTYPE IS '결재종류';
COMMENT ON COLUMN SGN_SIGN.SSRESULT IS '결재결과';
COMMENT ON COLUMN SGN_SIGN.SSCOMMENT IS '코멘트';
COMMENT ON COLUMN SGN_SIGN.RECEIVEDATE IS '받은일자';
COMMENT ON COLUMN SGN_SIGN.SIGNDATE IS '결재일자';
COMMENT ON COLUMN SGN_SIGN.USERNO IS '사용자번호';
COMMENT ON COLUMN SGN_SIGN.USERPOS IS '직위';

DROP TABLE COM_MENU;
CREATE TABLE COM_MENU
(
    MNU_NO           NUMBER(10) NOT NULL,
    MNU_PARENT       NUMBER(10),
    MNU_TYPE         VARCHAR2(10),
    MNU_NM           VARCHAR2(100),
    MNU_MSG_CD       VARCHAR2(100),
    MNU_DESC         VARCHAR2(400),
    MNU_TARGET       VARCHAR2(100),
    MNU_FILENM       VARCHAR2(100),
    MNU_IMGPATH      VARCHAR2(100),
    MNU_CUSTOM       VARCHAR2(400),
    MNU_DESKTOP      CHAR(1) DEFAULT 'N',
    MNU_MOBILE       CHAR(1) DEFAULT 'N',
    MNU_ORDER        NUMBER(10),
    MNU_CERT_TYPE    VARCHAR2(10),
    MNU_EXTN_CONN_YN CHAR(1) DEFAULT 'N',
    MNU_START_HOUR   VARCHAR2(5),
    MNU_END_HOUR     VARCHAR2(5),
    REGDATE          TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    REGUSERNO        NUMBER(10),
    CHGDATE          TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CHGUSERNO        NUMBER(10),
    DELETEFLAG       CHAR(1),
    CONSTRAINT PK_COM_MENU PRIMARY KEY (MNU_NO)
);
COMMENT ON TABLE COM_MENU IS '메뉴정보';
COMMENT ON COLUMN COM_MENU.MNU_NO           IS '메뉴ID';
COMMENT ON COLUMN COM_MENU.MNU_PARENT       IS '상위메뉴ID';
COMMENT ON COLUMN COM_MENU.MNU_TYPE         IS '메뉴유형코드-팝업,컨텐츠';
COMMENT ON COLUMN COM_MENU.MNU_NM           IS '메뉴명';
COMMENT ON COLUMN COM_MENU.MNU_MSG_CD       IS '메뉴 다국어 코드';
COMMENT ON COLUMN COM_MENU.MNU_DESC         IS '설명';
COMMENT ON COLUMN COM_MENU.MNU_TARGET       IS '메뉴링크';
COMMENT ON COLUMN COM_MENU.MNU_FILENM       IS '파일명';
COMMENT ON COLUMN COM_MENU.MNU_IMGPATH      IS '이미지경로';
COMMENT ON COLUMN COM_MENU.MNU_CUSTOM       IS '커스텀태그';
COMMENT ON COLUMN COM_MENU.MNU_DESKTOP      IS '데스크탑버전 사용여부';
COMMENT ON COLUMN COM_MENU.MNU_MOBILE       IS '모바일버전 사용여부';
COMMENT ON COLUMN COM_MENU.MNU_ORDER        IS '정렬순서';
COMMENT ON COLUMN COM_MENU.MNU_CERT_TYPE    IS '인증구분코드';
COMMENT ON COLUMN COM_MENU.MNU_EXTN_CONN_YN IS '외부연결여부';
COMMENT ON COLUMN COM_MENU.MNU_START_HOUR   IS '사용시작시';
COMMENT ON COLUMN COM_MENU.MNU_END_HOUR     IS '사용종료시';
COMMENT ON COLUMN COM_MENU.REGDATE          IS '등록일자';
COMMENT ON COLUMN COM_MENU.REGUSERNO        IS '등록자';
COMMENT ON COLUMN COM_MENU.CHGDATE          IS '수정일자';
COMMENT ON COLUMN COM_MENU.CHGUSERNO        IS '수정자';
COMMENT ON COLUMN COM_MENU.DELETEFLAG       IS '삭제여부';

CREATE TABLE TBL_BUCKET (
   BKNO NUMBER(10) NOT NULL,
   STATE BLOB   NULL,
   CONSTRAINT PK_TBL_BUCKET PRIMARY KEY (BKNO)
);

-- DROP FUNCTION uf_datetime2string;
CREATE OR REPLACE FUNCTION uf_datetime2string(dt_ IN DATE) RETURN VARCHAR2 IS
    ti NUMBER;
    ret_ VARCHAR2(10);
BEGIN
    ti := (SYSDATE - dt_) * 24 * 60;

    IF ti < 1 THEN
        ret_ := '방금';
    ELSIF ti < 60 THEN
        ret_ := TO_CHAR(FLOOR(ti)) || '분전';
    ELSIF ti < 60 * 24 THEN
        IF TRUNC(SYSDATE) - TRUNC(dt_) = 1 THEN
            ret_ := '어제';
ELSE
            ret_ := TO_CHAR(FLOOR(ti / 60)) || '시간전';
END IF;
    ELSIF ti < 60 * 24 * 7 THEN
        ret_ := TO_CHAR(FLOOR(ti / 60 / 24)) || '일전';
    ELSIF ti < 60 * 24 * 7 * 4 THEN
        ret_ := TO_CHAR(FLOOR(ti / 60 / 24 / 7)) || '주전';
    ELSIF MONTHS_BETWEEN(SYSDATE, dt_) < 1 THEN
        ret_ := '지난달';
    ELSIF MONTHS_BETWEEN(SYSDATE, dt_) < 13 THEN
        IF FLOOR(MONTHS_BETWEEN(SYSDATE, dt_) / 12) = 1 THEN
            ret_ := '작년';
ELSE
            ret_ := TO_CHAR(FLOOR(MONTHS_BETWEEN(SYSDATE, dt_))) || '달전';
END IF;
ELSE
        ret_ := TO_CHAR(FLOOR(MONTHS_BETWEEN(SYSDATE, dt_) / 12)) || '년전';
END IF;

RETURN ret_;
END;
/
CREATE OR REPLACE FUNCTION makeCalendar(startdate VARCHAR2, enddate VARCHAR2) IS
    sdate DATE := TO_DATE(startdate, 'YYYY-MM-DD');
    edate DATE := TO_DATE(enddate, 'YYYY-MM-DD');
BEGIN
    DBMS_OUTPUT.PUT_LINE('sdate=' || sdate);
    DBMS_OUTPUT.PUT_LINE('edate=' || edate);

    IF sdate IS NULL THEN
SELECT
    MAX(CDDATE) + 1,
    MAX(CDDATE) + 300
INTO sdate, edate
FROM COM_DATE;
END IF;

    DBMS_OUTPUT.PUT_LINE('sdate=' || TO_CHAR(sdate, 'YYYY-MM-DD'));
    DBMS_OUTPUT.PUT_LINE('edate=' || TO_CHAR(edate, 'YYYY-MM-DD'));

    IF edate <= sdate THEN
        DBMS_OUTPUT.PUT_LINE('edate <= sdate RET');
        RETURN;
END IF;

    WHILE sdate <= edate LOOP
        DBMS_OUTPUT.PUT_LINE('LOOP ' || TO_CHAR(sdate, 'YYYY-MM-DD'));

INSERT INTO COM_DATE (CDDATE, CDYEAR, CDMM, CDDD, CDWEEKOFYEAR, CDWEEKOFMONTH, CDWEEK, CDDAYOFWEEK)
SELECT
    sdate,
    EXTRACT(YEAR FROM sdate),
    EXTRACT(MONTH FROM sdate),
    EXTRACT(DAY FROM sdate),
    TO_NUMBER(TO_CHAR(sdate, 'IW')),
    FLOOR((EXTRACT(DAY FROM sdate) - 1) / 7) + 1,
    TO_NUMBER(TO_CHAR(sdate, 'WW')),
    TO_NUMBER(TO_CHAR(sdate, 'D'))
FROM dual;

sdate := sdate + 1;
END LOOP;

    DBMS_OUTPUT.PUT_LINE('LOOP END');
END;
/
---- end makeCalendar

-- DROP FUNCTION getColor4Alert;
CREATE OR REPLACE FUNCTION getColor4Alert(
    tsstartdate_ IN VARCHAR2,
    tsenddate_ IN VARCHAR2,
    tsendreal_ IN VARCHAR2,
    tsrate_ IN INTEGER
) RETURN VARCHAR2 IS
    bgcolor_ VARCHAR2(10);
    today_ DATE := SYSDATE;
    tsstartdate DATE := TO_DATE(tsstartdate_, 'YYYY-MM-DD');
    tsenddate DATE := TO_DATE(tsenddate_, 'YYYY-MM-DD');
    tsendreal DATE := CASE WHEN tsendreal_ IS NOT NULL AND tsendreal_ != '' THEN TO_DATE(tsendreal_, 'YYYY-MM-DD') ELSE NULL END;
BEGIN
    -- 초기 백그라운드 색상 설정
    bgcolor_ := 'gray';

    IF tsrate_ < 100 THEN
        IF tsstartdate > today_ THEN
            bgcolor_ := 'gray';
        ELSIF tsenddate < today_ THEN
            bgcolor_ := 'red';
        ELSIF (today_ - tsstartdate) < (tsenddate - today_) THEN
            bgcolor_ := 'green';
        ELSIF (today_ - tsstartdate) >= (tsenddate - today_) THEN
            bgcolor_ := 'yellow';
END IF;
ELSE
        IF tsendreal_ IS NOT NULL AND tsendreal <= tsenddate THEN
            bgcolor_ := 'green';
ELSE
            bgcolor_ := 'orange';
END IF;
END IF;

RETURN bgcolor_;
END;
/
