spring.profiles.group.dev=common
spring.profiles.group.local=common
spring.profiles.group.prod=common
spring.profiles.group.stag=common
spring.profiles.active=local

# Bean definition overriding - allow custom beans to override auto-configured ones
spring.main.allow-bean-definition-overriding=true