-- DROP SEQUENCE IF EXISTS PRNO_SEQ;
CREATE SEQUENCE PRNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS TSNO_SEQ;
CREATE SEQUENCE TSNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS FILENO_TASK_SEQ;
CREATE SEQUENCE FILENO_TASK_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS DEPTNO_SEQ;
CREATE SEQUENCE DEPTNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS USERNO_SEQ;
CREATE SEQUENCE USERNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS BRDNO_SEQ;
CREATE SEQUENCE BRDNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS FILENO_SEQ;
CREATE SEQUENCE FILENO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS BLNO_SEQ;
CREATE SEQUENCE BLNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS RENO_SEQ;
CREATE SEQUENCE RENO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS BGNO_SEQ;
CREATE SEQUENCE BGNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS CRNO_SEQ;
CREATE SEQUENCE CRNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS LNO_SEQ;
CREATE SEQUENCE LNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS EMNO_SEQ;
CREATE SEQUENCE EMNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS FILENO_EML_SEQ;
CREATE SEQUENCE FILENO_EML_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS EMINO_SEQ;
CREATE SEQUENCE EMINO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS SHNO_SEQ;
CREATE SEQUENCE SHNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS SSNO_SEQ;
CREATE SEQUENCE SSNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS DOCNO_SEQ;
CREATE SEQUENCE DOCNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS FILENO_SGN_SEQ;
CREATE SEQUENCE FILENO_SGN_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS DTNO_SEQ;
CREATE SEQUENCE DTNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS SPNO_SEQ;
CREATE SEQUENCE SPNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS SSNO_SIGN_SEQ;
CREATE SEQUENCE SSNO_SIGN_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS CDNO_SEQ;
CREATE SEQUENCE CDNO_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE IF EXISTS MNU_NO_SEQ;
CREATE SEQUENCE MNU_NO_SEQ START WITH 1 INCREMENT BY 1;